package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;


public class Asteroid extends Place 
{
	private Integer CrustThickness;
	private Integer HoleDepth;
	private Boolean CoreIsEmpty;
	private RawMaterial corematerial;
	private ArrayList<SentientBeing> sentientbeings;
	private ArrayList<Place> neighbors;
	private BillOfMaterials radBill;
	
	public Asteroid()
	{
		
	}
	
	public void IncreaseHoleDepth() 
	{
		System.out.println("IncreaseHoleDepth()");
	}
	
	public void Explode()
	{
		System.out.println("Explode()");
		Scanner scanner = new Scanner(System.in);
		
		Boolean feltetel1 = radBill.CheckInventory(corematerial);
		
		System.out.println("CrustThickness == HoleDepth?");
		Boolean feltetel2 = false;
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			feltetel2 = true;
		}else if(input.equals("nem"))
		{
			feltetel2 = false;
		}
		
		Boolean feltetel3 = this.AtPerihelion();
		
		if((feltetel1 == true && feltetel2 == true && feltetel3 == true) || neighbors.isEmpty())
		{
			for(SentientBeing sb : sentientbeings)
			{
				sb.Explode();
			}
			
			corematerial.Perish();
			
			for(Place n : neighbors)
			{
				n.Explode();
			}
		}
		scanner.close();
	}
	
	public void DropBeing(SentientBeing being)
	{
		System.out.println("DropBeing()");
	}
	
	public void RegisterBeing(SentientBeing being)
	{
		System.out.println("RegisterBeing()");
	}
	
	public void DropMaterial() 
	{
		System.out.println("DropMaterial()");
	}
	
	public RawMaterial GetMaterial()
	{
		System.out.println("GetMaterial()");
		return null;
	}
	
	public Boolean IsEmpty()
	{
		System.out.println("Üres az aszteroida?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			scanner.close();
			return true;
		}else if(input.equals("nem"))
		{
			scanner.close();
			return false;
		}
		scanner.close();
		return false;
	}
	
	public void SetMaterial(RawMaterial material, Settler settler)
	{
		System.out.println("SetMaterial()");
	}
	
	public void DropNeighbor(Place neighbor)
	{
		System.out.println("DropNeighbor()");
	}
	
	public Boolean AtPerihelion()
	{
		System.out.println("Napközelben van az aszteroida?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			scanner.close();
			return true;
		}else if(input.equals("nem"))
		{
			scanner.close();
			return false;
		}
		scanner.close();
		return false;
	}
	
	public void AddNeighbor(Place neighbor)
	{
		System.out.println("AddNeighbor()");
	}
	
	public void SolarWindDeath()
	{
		System.out.println("SolarWindDeath()");
		Scanner scanner = new Scanner(System.in);
		
		System.out.println("CrustThickness == HoleDepth?");
		Boolean feltetel1 = false;
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			feltetel1 = true;
		}else if(input.equals("nem"))
		{
			feltetel1 = false;
		}
		
		if(this.IsEmpty() == false || feltetel1 == false)
		{
			for(SentientBeing sb : sentientbeings)
			{
				sb.Die();
			}
		}
		scanner.close();
	}
	
	public void CheckPerihelionReaction()
	{
		System.out.println("CheckPerihelionReaction()");
		corematerial.PerihelionReaction();
	}
	
	public void StepBeings()
	{
		System.out.println("StepBeings()");
		for(SentientBeing sb : sentientbeings)
		{
			sb.Step();
		}
	}

}
