package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Asteroid extends Place {
	private Integer CrustThickness;
	private Integer HoleDepth;
	private Boolean CoreIsEmpty;
	private RawMaterial corematerial;
	private SentientBeing sentientbeings;
	private Place neighbors;
	public void IncreaseHoleDepth() {
	}
	
	public void Explode() {
	}
	
	public void DropBeing(SentientBeing being) {
	}
	
	public void RegisterBeing(SentientBeing being) {
	}
	
	public void DropMaterial() {
	}
	
	public RawMaterial GetMaterial() {
		return corematerial;
	}
	
	public Boolean IsEmpty() {
		return CoreIsEmpty;
	}
	
	public void SetMaterial(RawMaterial material, Settler settler) {
	}
	
	public void DropNeighbor(Asteroid neighbor) {
	}
	
	public Boolean AtPerihelion() {
		return CoreIsEmpty;
	}
	
	public void AddNeighbor(Place neighbor) {
	}
	
	public void SolarWindDeath() {
	}
	
	public void CheckPerihelionReaction() {
	}
	
	public void StepBeings() {
	}

	

}
