package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;


public class Asteroid extends Place 
{
	private Integer CrustThickness;
	private Integer HoleDepth;
	private Boolean CoreIsEmpty;
	private RawMaterial corematerial;
	private ArrayList<SentientBeing> sentientbeings;
	private ArrayList<Place> neighbors;
	private BillOfMaterials radBill;
	
	public Asteroid()
	{
		Logger.MethodCall("Asteroid()");
		sentientbeings = new ArrayList<SentientBeing>();
		neighbors = new ArrayList<Place>();
		Logger.MethodReturn("");
	}
	public void SetCore(RawMaterial rm) {
		this.corematerial = rm;
	}
	
	public void SetBill(BillOfMaterials radbill) {
		this.radBill = radbill;
	}
	public void IncreaseHoleDepth() 
	{
		Logger.MethodCall("IncreaseHoleDepth()");
		Logger.MethodReturn("void");
	}
	
	public void Explode()
	{
		Logger.MethodCall("Explode()");
		Boolean feltetel1 = false;
		if(corematerial != null)
		{
			ArrayList<RawMaterial> corelist = new ArrayList<RawMaterial>();
			corelist.add(corematerial);
			feltetel1 = radBill.CheckInventory(corelist);
		}
		
		Logger.UserQuestion("CrustThickness == HoleDepth?");
		Boolean feltetel2 = false;
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			feltetel2 = true;
		}else if(input.equals("2"))
		{
			feltetel2 = false;
		}
		
		Boolean feltetel3 = this.AtPerihelion();
		
		if((feltetel1 == true && feltetel2 == true && feltetel3 == true) || neighbors.isEmpty())
		{
			for(SentientBeing sb : sentientbeings)
			{
				sb.Explode();
			}
			
			corematerial.Perish();
			
			for(Place n : neighbors)
			{
				n.Explode();
			}
		}
		Logger.MethodReturn("void");
	}
	
	public void DropBeing(SentientBeing being)
	{
		Logger.MethodCall("DropBeing()");
		Logger.MethodReturn("void");
	}
	
	public void RegisterBeing(SentientBeing being)
	{
		Logger.MethodCall("RegisterBeing()");
		sentientbeings.add(being);
		Logger.MethodReturn("void");
	}
	
	public void DropMaterial() 
	{
		Logger.MethodCall("DropMaterial()");
		Logger.MethodReturn("void");
	}
	
	public RawMaterial GetMaterial()
	{
		Logger.MethodCall("GetMaterial()");
		Logger.MethodReturn("RawMaterial");
		return this.corematerial;
	}
	
	public Boolean IsEmpty()
	{
		Logger.MethodCall("IsEmpty()");
		Logger.UserQuestion("�res az aszteroida?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			Logger.MethodReturn("Boolean: true");
			return true;
		}else if(input.equals("2"))
		{
			Logger.MethodReturn("Boolean: false");
			return false;
		}
		Logger.MethodReturn("Boolean: false");
		return false;
	}
	
	public void SetMaterial(RawMaterial material, Settler settler)
	{
		Logger.MethodCall("SetMaterial()");
		Logger.MethodReturn("void");
	}
	
	public void DropNeighbor(Place neighbor)
	{
		Logger.MethodCall("DropNeighbor()");
		Logger.MethodReturn("void");
	}
	
	public Boolean AtPerihelion()
	{
		Logger.MethodCall("AtPerihelion()");
		Logger.UserQuestion("Is the asteroid at Perihelion?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			Logger.MethodReturn("Boolean: true");
			return true;
		}else if(input.equals("2"))
		{
			Logger.MethodReturn("Boolean: false");
			return false;
		}
		Logger.MethodReturn("Boolean: false");
		return false;
	}
	
	public void AddNeighbor(Place neighbor)
	{
		Logger.MethodCall("AddNeighbor()");
		Logger.MethodReturn("void");
	}
	
	public void SolarWindDeath()
	{
		Logger.MethodCall("SolarWindDeath()");
		Scanner scanner = new Scanner(System.in);
		
		Logger.UserQuestion("CrustThickness == HoleDepth?");
		Boolean feltetel1 = false;
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			feltetel1 = true;
		}else if(input.equals("2"))
		{
			feltetel1 = false;
		}
		
		if(this.IsEmpty() == false || feltetel1 == false)
		{
			for(SentientBeing sb : sentientbeings)
			{
				sb.Die();
			}
		}
		Logger.MethodReturn("void");
	}
	
	public void CheckPerihelionReaction()
	{
		Logger.MethodCall("CheckPerihelionReaction()");
		corematerial.PerihelionReaction();
		Logger.MethodReturn("void");
	}
	
	public void StepBeings()
	{
		Logger.MethodCall("StepBeings()");
		for(SentientBeing sb : sentientbeings)
		{
			sb.Step();
		}
		Logger.MethodReturn("void");
	}

}
