package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillOfMaterials.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;

public class BillOfMaterials
{
	private ArrayList<RawMaterial> materials;
	
	
	public void setMaterials(ArrayList<RawMaterial> materials) {
		System.out.println("setMaterials(ArrayList<RawMaterial> materials))");
		this.materials = materials;
	}

	public Boolean CheckInventory(ArrayList<RawMaterial> inventory) 
	{
		System.out.println("CheckInventory(ArrayList<RawMaterial> inventory)");
		Scanner scanner = new Scanner(System.in);
		
		System.out.println("A feltételeket teljesíti az inventory?");
		Boolean feltetel = false;
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			feltetel = true;
		}else if(input.equals("nem"))
		{
			feltetel = false;
		}
		scanner.close();
		return feltetel;
	}
	
	public void AddMaterialToBill(RawMaterial material) 
	{
		System.out.println("AddMaterialToBill(ArrayList<RawMaterial> inventory)");
	}
	
	public ArrayList<RawMaterial> DeleteFromInventory(ArrayList<RawMaterial> inventory) 
	{
		System.out.println("DeleteFromInventory(ArrayList<RawMaterial> inventory)");
		return null;
	}
}
