package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillOfMaterials.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;

public class BillOfMaterials
{
	private ArrayList<RawMaterial> materials;
	
	public BillOfMaterials()
	{
		Logger.MethodCall("BillOfMaterials()");
		materials = new ArrayList<RawMaterial>();
		Logger.MethodReturn("");
	}
	
	public Boolean CheckInventory(ArrayList<RawMaterial> inventory) 
	{
		Logger.MethodCall("CheckInventory(ArrayList<RawMaterial> inventory)");
		Scanner scanner = new Scanner(System.in);
		
		Logger.UserQuestion("A feltételeket teljesíti az inventory?");
		Boolean feltetel = false;
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			feltetel = true;
			Logger.MethodReturn("Boolean: true");
		}else if(input.equals("2"))
		{
			feltetel = false;
			Logger.MethodReturn("Boolean: false");
		}
		scanner.close();
		return feltetel;
	}
	
	public void AddMaterialToBill(RawMaterial material) 
	{
		Logger.MethodCall("AddMaterialToBill(ArrayList<RawMaterial> inventory)");
		Logger.MethodReturn("void");
		materials.add(material);
	}
	
	public ArrayList<RawMaterial> DeleteFromInventory(ArrayList<RawMaterial> inventory) 
	{
		Logger.MethodCall("DeleteFromInventory(ArrayList<RawMaterial> inventory)");
		Logger.MethodReturn("ArrayList<RawMaterial>");
		return null;
	}
}
