package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coal.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Coal extends RawMaterial 
{
	public Coal() {

	}
	public void Perish() 
	{
		System.out.println("Perish()");
		this.SetAsteroid(null);
	}
	
	public String GetUniqueID() 
	{
		System.out.println("GetUniqueID()");
		return "Coal";
	}
	
	public void PerihelionReaction() 
	{
		System.out.println("PerihelionReaction()");
		
	}
	
}
