package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coal.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Coal extends RawMaterial 
{
	public void Perish() 
	{
		
	}
	
	public String GetUniqueID() 
	{
		
	}
	
	public void PerihelionReaction() 
	{
		
	}
	
}
