package asteroid;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControllerClass.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class ControllerClass
{
	private ArrayList<Asteroid> asteroids;
	private ArrayList<Settler> settlers;
	private ArrayList<Robot> robots;
	private SolarWind solarwind;
	private ArrayList<BillOfMaterials> bills;
	
	public ControllerClass() {
		System.out.println("ControllerClass()");
		asteroids = new ArrayList<Asteroid>();
		settlers = new ArrayList<Settler>();
		robots = new ArrayList<Robot>();
		bills = new ArrayList<BillOfMaterials>();
		InitAsteroids();
		InitSettlers();
		InitBills();
	}
	
	public void GameLoop()
	{
		System.out.println("GameLoop()");
	}
	
	public void InitAsteroids()
	{
		System.out.println("InitAsteroids()");
		ConnectAsteroids();
	}
	
	public void InitSettlers()
	{
		System.out.println("InitSettlers()");
		GetRandomAsteroid();
	}
	
	public void InitBills() 
	{
		System.out.println("InitBills()");
	}
	
	public void ConnectAsteroids() 
	{
		System.out.println("ConnectAsteroids()");
	}
	
	public Asteroid GetRandomAsteroid() 
	{
		System.out.println("GetRandomAsteroid()");
		return null;
	}
}
