package asteroid;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControllerClass.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class ControllerClass
{
	private ArrayList<Asteroid> asteroids;
	private ArrayList<Settler> settlers;
	private ArrayList<Robot> robots;
	private SolarWind solarwind;
	private ArrayList<BillOfMaterials> bills;
	
	public ControllerClass() {
		Logger.MethodCall("ControllerClass()");
		asteroids = new ArrayList<Asteroid>();
		settlers = new ArrayList<Settler>();
		robots = new ArrayList<Robot>();
		bills = new ArrayList<BillOfMaterials>();
		InitAsteroids();
		InitSettlers();
		InitBills();
		Logger.MethodReturn();
	}
	
	public void GameLoop()
	{
		Logger.MethodCall("GameLoop()");
		Logger.MethodReturn();
	}
	
	public void InitAsteroids()
	{
		Logger.MethodCall("InitAsteroids()");
		Asteroid a1 = new Asteroid();
		ConnectAsteroids();
		Logger.MethodReturn();
	}
	
	public void InitSettlers()
	{
		Logger.MethodCall("InitSettlers()");
		Settler s1 = new Settler();
		Asteroid a1 = GetRandomAsteroid();
		s1.setAsteroid(a1);
		Logger.MethodReturn();
	}
	
	public void InitBills() 
	{
		Logger.MethodCall("InitBills()");
		Logger.MethodReturn();
	}
	
	public void ConnectAsteroids() 
	{
		Logger.MethodCall("ConnectAsteroids()");
		Logger.MethodReturn();
	}
	
	public Asteroid GetRandomAsteroid() 
	{
		Logger.MethodCall("GetRandomAsteroid()");
		Logger.MethodReturn();
		return null;
	}
}
