package asteroid;

import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Ice extends RawMaterial 
{
	public Ice()
	{
		Logger.MethodCall("Ice()");
		Logger.MethodReturn("");
	}
	public void Perish() 
	{
		Logger.MethodCall("Perish()");
		this.SetAsteroid(null);
		Logger.MethodReturn("void");
	}
	
	public String GetUniqueID() 
	{
		Logger.MethodCall("GetUniqueID()");
		Logger.MethodReturn("String: Ice");
		return "Ice";
	}
	
	public void PerihelionReaction() 
	{
		Logger.MethodCall("PerihelionReaction()");
		Scanner sc = new Scanner(System.in);
		Logger.UserQuestion("Holedepth = CrustTickness?");
		String answer = sc.nextLine();
		if (answer.equals("1"))
		{
			this.asteroid.DropMaterial();
			this.Perish();
		}
		sc.close();
		Logger.MethodReturn("void");
	}

}
