package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iron.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Iron extends RawMaterial
{
	public void Perish()
	{
		
	}
	
	public String GetUniqueID()
	{
		return "Iron";
	}
	
	public void PerihelionReaction()
	{
		
	}
}
