package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iron.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Iron extends RawMaterial
{
	/**
	 * A vas konstruktora.
	 *
	 */
	public Iron()
	{
		Logger.MethodCall("Iron()");
		Logger.MethodReturn("");
	}
	
	/**
	 * A nyersanyagot elpusztito fuggveny.
	 */
	public void Perish()
	{
		Logger.MethodCall("Perish()");
		this.SetAsteroid(null);
		Logger.MethodReturn("void");
	}
	
	/**
	 * Az egyedi azonositot visszaado fuggveny. Vas esesteben 'Iron'.
	 */
	public String GetUniqueID()
	{
		Logger.MethodCall("GetUniqueID()");
		Logger.MethodReturn("String: Iron");
		return "Iron";
	}
	
	/**
	 * Az anyag reakciojat napkozelben kivalto absztrakt fuggveny.
	 * Vas eseteben nincs reakcio.
	 */
	public void PerihelionReaction()
	{
		Logger.MethodCall("PerihelionReaction()");
		Logger.MethodReturn("void");
	}
}
