package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iron.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Iron extends RawMaterial
{
	public Iron()
	{
		Logger.MethodCall("Iron()");
		Logger.MethodReturn("");
	}
	public void Perish()
	{
		Logger.MethodCall("Perish()");
		this.SetAsteroid(null);
		Logger.MethodReturn("void");
	}
	
	public String GetUniqueID()
	{
		Logger.MethodCall("GetUniqueID()");
		Logger.MethodReturn("String: Iron");
		return "Iron";
	}
	
	public void PerihelionReaction()
	{
		Logger.MethodCall("PerihelionReaction()");
		Logger.MethodReturn("void");
	}
}
