package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Place.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public abstract class Place {
	public abstract void RegisterBeing(SentientBeing being);
	public abstract void Explode();
}
