package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RawMaterial.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public abstract class RawMaterial
{
	private Asteroid asteroid;
	public void Perish()
	{
		
	}
	
	public void SetAsteroid(Asteroid asteroid)
	{
		
	}
	
	public abstract String GetUniqueID();
	
	public abstract void PerihelionReaction();
}
