package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RawMaterial.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public abstract class RawMaterial
{
	protected Asteroid asteroid;
	public void Perish()
	{
		Logger.MethodCall("Perish()");
		this.SetAsteroid(null);
		Logger.MethodReturn("void");
	}
	
	public void SetAsteroid(Asteroid asteroid)
	{
		Logger.MethodCall("SetAsteroid(Asteroid asteroid)");
		this.asteroid = asteroid;
		Logger.MethodReturn("void");
	}
	
	public abstract String GetUniqueID();
	
	public abstract void PerihelionReaction();
}
