package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.Scanner;

public class Robot extends SentientBeing
{
	public Robot()
	{
		Logger.MethodCall("Robot()");
		Logger.MethodReturn("");
	}
	
	public void Move(Place place) 
	{
		Logger.MethodCall("Move(Place place)");
		this.location.DropBeing(this);
		place.RegisterBeing(this);
		Logger.MethodReturn("void");
	}
	
	public void Drill()
	{
		Logger.MethodCall("Drill()");
		Logger.UserQuestion("Can the robot drill?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			location.IncreaseHoleDepth();
		}
		Logger.MethodReturn("void");
	}	
	
	public void Die() 
	{
		Logger.MethodCall("Die()");
		location.DropBeing(this);
		Logger.MethodReturn("void");
	}
	
	public void Explode()
	{
		Logger.MethodCall("Explode()");
		Scanner scanner = new Scanner(System.in);
		Logger.UserQuestion("Does the asteroid have more neighbors?");
		String input = scanner.nextLine();
		if(input.equals("2")) {
			Die();
		} else {
			Move(null);
		}
		Logger.MethodReturn("void");
	}
	
	public void Step() 
	{
		Logger.MethodCall("Step()");
		Scanner scanner = new Scanner(System.in);
		Logger.UserQuestionRobot("Drill or move the robot?");
		String input = scanner.nextLine();
		if(input.equals("1")) {
			Logger.Message("Refer to test 2");
		} else if(input.equals("2")) {
			Logger.Message("Refer to test 4");
		}
		Logger.MethodReturn("void");
		//scanner.close();
	}
}
