package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.Scanner;

public class Robot extends SentientBeing
{
	public Robot()
	{
		Logger.MethodCall("Robot()");
		Logger.MethodReturn("");
	}
	
	public void Move(Place place) 
	{
		Logger.MethodCall("Move(Place place)");
		this.location.DropBeing(this);
		place.RegisterBeing(this);
		Logger.MethodReturn("void");
	}
	
	public void Drill()
	{
		Logger.MethodCall("Drill()");
		Logger.UserQuestion("Meg tudja fúrni a robot?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			location.IncreaseHoleDepth();
		}
		scanner.close();
		Logger.MethodReturn("void");
	}	
	
	public void Die() 
	{
		Logger.MethodCall("Die()");
		location.DropBeing(this);
		Logger.MethodReturn("void");
	}
	
	public void Explode()
	{
		Logger.MethodCall("Explode()");
		Scanner scanner = new Scanner(System.in);
		Logger.UserQuestion("Van több szomszédja az aszteroidának?");
		String input = scanner.nextLine();
		scanner.close();
		if(input.equals("2")) {
			Die();
		} else {
			Move(null);
		}
		Logger.MethodReturn("void");
	}
	
	public void Step() 
	{
		Logger.MethodCall("Step()");
		Scanner scanner = new Scanner(System.in);
		Logger.UserQuestion("Fúrjon vagy lépjen a robot? (1=fúr, 2=lép)");
		String input = scanner.nextLine();
		if(input.equals("1")) {
			this.Drill();
		} else if(input.equals("2")) {
			//random aszteroida a teszt kedvéért; nincsen szomszédja.
			Asteroid a = new Asteroid();
			this.Move(a);
		}
		Logger.MethodReturn("void");
		//scanner.close();
	}
}
