package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SentientBeing.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public abstract class SentientBeing {
	private Asteroid location;
	public abstract void Move(Place place);
	public abstract void Drill();
	public abstract void Die();
	public abstract void Explode();
	public abstract void Step();
}
