package asteroid;

import java.util.ArrayList;
import java.util.Scanner;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Settler.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Settler extends SentientBeing {
	private ArrayList<RawMaterial> carriedmaterials;
	private ArrayList<BillOfMaterials> bills;
	private ArrayList<TeleportGate> carriedteleports;
	public Settler() 
	{
		
		//carriedmaterials = new ArrayList<RawMaterial>();
		//carriedteleports = new ArrayList<TeleportGate>();
		bills= new ArrayList<BillOfMaterials>();
		bills.add(new BillOfMaterials());
		bills.add(new BillOfMaterials());
		bills.add(new BillOfMaterials());
	}
	public void Drill() 
	{
		System.out.println("Még tudja fúrni a telepes?(igen/nem)");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen")) {//TODO tudni kell, hogy még furhatja-e
			location.IncreaseHoleDepth();//TODO 
		}
		scanner.close();
	}
	
	public void Mine() 
	{
		System.out.println("Fér-e a telepes zsebébe még anyag?(igen/nem)");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen")) {
			if(!location.IsEmpty()) {
				RawMaterial rm=location.GetMaterial();
				AddCarriedMaterial(null);
				rm.SetAsteroid(null);
				location.DropMaterial();
			}
		}
		scanner.close();
	}
	
	public void Die() 
	{
		System.out.println("Die()");
		for(RawMaterial item:carriedmaterials) {
			item.Perish();
		}
		for(TeleportGate item:carriedteleports) {
			item.Explode();
		}
	}
	
	public void AddCarriedMaterial(RawMaterial material) {
		System.out.println("AddCarriedMaterial()");
		carriedmaterials.add(material);
	}
	
	public void Explode() 
	{
		System.out.println("Explode()");
	}
	
	public void BuildRobot() 
	{
		System.out.println("BuildRobot()");

		//TODO robo bill hiánya van itten, miképp kérjem el a bills-bõl pont a drágát?
		//én úgy vettem, hogy pont az egyes(és nem elsõ) lesz az.
		//TODO a BOM-nak arraylistet kéne fogadnia
		Boolean feltetel1 = bills.get(1).CheckInventory(null);
		if(feltetel1) 
		{
			location.RegisterBeing(new Robot());
			bills.get(1).DeleteFromInventory(null);
		}

	}
	
	public void BuildTeleportGatePair() 
	{
		System.out.println("BuildTeleportGatePair()");

		//TODO telegate bill hiánya van itten, miképp kérjem el a bills-bõl pont a drágát?
		//én úgy vettem, hogy pont az kettes(és nem második) lesz az.
		//TODO a BOM-nak arraylistet kéne fogadnia
		
		Boolean feltetel1 = bills.get(2).CheckInventory(null);
		if(feltetel1) 
		{
			TeleportGate t1=new TeleportGate();
			TeleportGate t2=new TeleportGate();
			
			bills.get(2).DeleteFromInventory(null);
			
			t1.SetSibling(t2);
			t2.SetSibling(t1);
		}
		
	}
	
	public void FillAsteroid(RawMaterial material) 
	{
		System.out.println("FillAsteroid()");

		System.out.println("Tud-e a telepes bepakolni?(igen/nem)");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen")) {
			location.SetMaterial(material, this);
		}
		scanner.close();
	}
	
	
	public void Move(Place place) 
	{
		location.DropBeing(this);
		place.RegisterBeing(this);
	}
	
	public void PutTeleportGateOnAsteroid() 
	{
		System.out.println("PutTeleportGateOnAsteroid()");

		System.out.println("Van-e a telepes zsebében teleport?(igen/nem)");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("igen")) {
			TeleportGate t=carriedteleports.get(carriedteleports.size()-1);
			location.AddNeighbor(t);
		}
		scanner.close();
	}
	
	public void Step() 
	{
		System.out.println("Step()");

		//System.out.println("Mit csináljona a telepes? 1=mozogo egy aszteroidára,2=ás, 3=bányász,4=anyagot rak vissza,5=robotot épít, 6=teleportot épít, 7=teleportot helyez le");
		
	}
	
	public void DropCarriedMaterial(RawMaterial material) {
		System.out.println("DropCarriedMaterial()");

		//carriedmaterials.remove(material);
	}
	
	public void DropCarriedTeleport(TeleportGate teleport) 
	{
		System.out.println("DropCarriedTeleport()");

		//carriedteleports.remove(teleport);
	}
}
