package asteroid;

import java.util.ArrayList;
import java.util.Scanner;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Settler.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Settler extends SentientBeing {
	private ArrayList<RawMaterial> carriedmaterials;
	private ArrayList<BillOfMaterials> bills;
	private ArrayList<TeleportGate> carriedteleports;
	public Settler() 
	{
		Logger.MethodCall("Settler()");
		carriedmaterials = new ArrayList<RawMaterial>();
		carriedteleports = new ArrayList<TeleportGate>();
		bills = new ArrayList<BillOfMaterials>();
		bills.add(new BillOfMaterials());
		bills.add(new BillOfMaterials());
		bills.add(new BillOfMaterials());
		Logger.MethodReturn("");
	}
	public void addteleport(TeleportGate tg) {
		this.carriedteleports.add(tg);
	}
	public void Drill() 
	{
		Logger.MethodCall("Drill()");
		Logger.UserQuestion("Can the settler drill?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1")) {//TODO tudni kell, hogy m�g furhatja-e
			location.IncreaseHoleDepth();//TODO 
		}
		Logger.MethodReturn("void");
	}
	
	public void Mine() 
	{
		Logger.MethodCall("Mine()");
		Logger.UserQuestion("Does it still fit in the settler's invetory?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1")) {
			if(!location.IsEmpty()) {
				RawMaterial rm=location.GetMaterial();
				AddCarriedMaterial(rm);
				rm.SetAsteroid(null);
				location.DropMaterial();
			}
		}
		Logger.MethodReturn("void");
	}
	
	public void Die() 
	{
		Logger.MethodCall("Die()");
		for(RawMaterial item:carriedmaterials) {
			item.Perish();
		}
		for(TeleportGate item:carriedteleports) {
			item.Explode();
		}
		Logger.MethodReturn("void");
	}
	
	public void AddCarriedMaterial(RawMaterial material)
	{
		Logger.MethodCall("AddCarriedMaterial()");
		carriedmaterials.add(material);
		Logger.MethodReturn("void");
	}
	
	public void Explode() 
	{
		Logger.MethodCall("Explode()");
		Logger.MethodReturn("void");
	}
	
	public void BuildRobot() 
	{
		Logger.MethodCall("BuildRobot()");

		//TODO robo bill hi�nya van itten, mik�pp k�rjem el a bills-b�l pont a dr�g�t?
		//�n �gy vettem, hogy pont az egyes(�s nem els�) lesz az.
		//TODO a BOM-nak arraylistet k�ne fogadnia
		Boolean feltetel1 = bills.get(1).CheckInventory(null);
		if(feltetel1) 
		{
			location.RegisterBeing(new Robot());
			bills.get(1).DeleteFromInventory(null);
		}
		Logger.MethodReturn("void");
	}
	
	public void BuildTeleportGatePair() 
	{
		Logger.MethodCall("BuildTeleportGatePair()");

		//TODO telegate bill hi�nya van itten, mik�pp k�rjem el a bills-b�l pont a dr�g�t?
		//�n �gy vettem, hogy pont az kettes(�s nem m�sodik) lesz az.
		//TODO a BOM-nak arraylistet k�ne fogadnia
		
		Boolean feltetel1 = bills.get(2).CheckInventory(null);
		if(feltetel1) 
		{
			TeleportGate t1=new TeleportGate();
			TeleportGate t2=new TeleportGate();
			
			bills.get(2).DeleteFromInventory(null);
			
			t1.SetSibling(t2);
			t2.SetSibling(t1);
		}
		Logger.MethodReturn("void");
	}
	
	public void FillAsteroid(RawMaterial material) 
	{
		Logger.MethodCall("FillAsteroid()");

		Logger.UserQuestion("Can the settler fill the asteroid?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("yes")) {
			location.SetMaterial(material, this);
		}
		Logger.MethodReturn("void");
	}
	
	
	public void Move(Place place) 
	{
		Logger.MethodCall("Move(Place place)");
		location.DropBeing(this);
		place.RegisterBeing(this);
		Logger.MethodReturn("void");
	}
	
	public void PutTeleportGateOnAsteroid() 
	{
		Logger.MethodCall("PutTeleportGateOnAsteroid()");

		Logger.UserQuestion("Does the settler have a teleportgate?");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.nextLine();
		if(input.equals("1")) {
			TeleportGate t=new TeleportGate();
			t.GetAsteroid();
			Logger.UserQuestion("Is the settler on the same asteroid as the teleportgate's sibling?");
			scanner = new Scanner(System.in);
			String input2 = scanner.nextLine();
			if(input2.equals("1")) {
				Asteroid TestLocation=new Asteroid();
				TestLocation.AddNeighbor(t);
				t.SetAsteroid(TestLocation);
				t.DropOwner();
				DropCarriedTeleport(t);
			}
		}
		Logger.MethodReturn("void");
	}
	
	public void Step() 
	{
		Logger.MethodCall("Step()");
		Logger.UserQuestionSettler("What will the settler do?");
		Scanner scanner = new Scanner(System.in);
		String input = "-1";
			input = scanner.nextLine();
			switch(Integer.parseInt(input))
			{
				case 1: Logger.Message("Refer to test 3"); break;
				case 2: Logger.Message("Refer to test 1"); break;
				case 3: Logger.Message("Refer to test 5"); break;
				case 4: Logger.Message("Refer to test 6"); break;
				case 5: Logger.Message("Refer to test 7"); break;
				case 6: Logger.Message("Refer to test 8"); break;
				case 7: Logger.Message("Refer to test 9"); break;
			}
		
		Logger.MethodReturn("void");
	}
	
	public void DropCarriedMaterial(RawMaterial material)
	{
		Logger.MethodCall("DropCarriedMaterial()");
		Logger.MethodReturn("void");
	}
	
	public void DropCarriedTeleport(TeleportGate teleport) 
	{
		Logger.MethodCall("DropCarriedTeleport()");
		Logger.MethodReturn("void");
	}
	
}
