package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolarWind.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;

public class SolarWind
{
	private ArrayList<SentientBeing> sentientbeings;
	
	public SolarWind()
	{
		Logger.MethodCall("SolarWind()");
		sentientbeings = new ArrayList<SentientBeing>();
		Logger.MethodReturn("");
	}
	
	public void solarWind(ArrayList<Asteroid> asteroids)
	{
		Logger.MethodCall("SolarWind()");
		Scanner scanner = new Scanner(System.in);
		Logger.UserQuestion("Is there a solar wind?");
		Boolean feltetel = false;
		String input = scanner.nextLine();
		if(input.equals("1"))
		{
			feltetel = true;
		}else if(input.equals("2"))
		{
			feltetel = false;
		}
		
		
		if(feltetel == true)
		{
			for(Asteroid a : asteroids)
			{
				a.SolarWindDeath();
			}	
		}
		Logger.MethodReturn("void");
	}
}
