package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolarWind.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class SolarWind
{
	private SentientBeing sentientbeings;
	public void SolarWind(Asteroid asteroids)
	{
		
	}
}
