package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolarWind.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Scanner;

public class SolarWind
{
	private SentientBeing sentientbeings;
	public SolarWind(ArrayList<Asteroid> asteroids)
	{
		System.out.println("SolarWind()");
		Scanner scanner = new Scanner(System.in);
		
		System.out.println("Napszél van?");
		Boolean feltetel = false;
		String input = scanner.nextLine();
		if(input.equals("igen"))
		{
			feltetel = true;
		}else if(input.equals("nem"))
		{
			feltetel = false;
		}
		
		
		if(feltetel == true)
		{
			for(Asteroid a : asteroids)
			{
				a.SolarWindDeath();
			}	
		}
		
		scanner.close();
	}
}
