package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleportGate.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class TeleportGate extends Place 
{
	private TeleportGate sibling;
	private Asteroid asteroid;
	private Settler owner;
	public void SetSibling(TeleportGate sibling) 
	{
		
	}
	
	public void SetAsteroid(Asteroid asteroid) 
	{
		
	}
	
	public Asteroid GetAsteroid() 
	{
		
	}
	
	public TeleportGate GetSibling()
	{
		
	}
	
	
	public void DropOwner()
	{
		
	}
	
	public Settler GetOwner()
	{
		
	}
	
	public void RegisterBeing(SentientBeing being)
	{
		
	}
	
	public void Explode() 
	{
		
	}
}
