package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleportGate.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.Scanner;

public class TeleportGate extends Place 
{
	private TeleportGate sibling;
	private Asteroid asteroid;
	private Settler owner;
	
	public TeleportGate()
	{
		Logger.MethodCall("TeleportGate()");
		Logger.MethodReturn("");
	}
	
	public void SetOwner(Settler s) {
		owner = s;
	}
	
	public void SetSibling(TeleportGate sibling) 
	{
		Logger.MethodCall("SetSibling()");
		Logger.MethodReturn("void");
		this.sibling = sibling;
	}
	
	public void SetAsteroid(Asteroid asteroid) 
	{
		Logger.MethodCall("SetAsteroid()");
		Logger.MethodReturn("void");
		this.asteroid = asteroid;
	}
	
	public Asteroid GetAsteroid() 
	{
		Logger.MethodCall("GetAsteroid()");
		Logger.MethodReturn("Asteroid");
		return this.asteroid;
	}
	
	public TeleportGate GetSibling()
	{
		Logger.MethodCall("GetSibling()");
		Logger.MethodReturn("TeleportGate");
		return this.sibling;
	}
	
	
	public void DropOwner()
	{
		Logger.MethodCall("DropOwner()");
		Logger.MethodReturn("void");
	}
	
	public Settler GetOwner()
	{
		Logger.MethodCall("GetOwner()");
		Logger.MethodReturn("Settler");
		return this.owner;
	}
	
	public void RegisterBeing(SentientBeing being)
	{
		Logger.MethodCall("RegisterBeing()");
		Logger.MethodReturn("void");
	}
	
	public void Explode() 
	{
		Logger.MethodCall("Explode()");		
		Asteroid a = this.GetAsteroid();	
		if(a != null)
		{
			asteroid.DropNeighbor(this);
		}else
		{
			owner.DropCarriedTeleport(this);
		}
		
		Asteroid a2 = this.sibling.GetAsteroid();
		if(a2 != null)
		{
			sibling.GetAsteroid().DropNeighbor(sibling);
			sibling.SetAsteroid(null);
		}else
		{
			sibling.GetOwner().DropCarriedTeleport(sibling);
		}
		Logger.MethodReturn("void");
	}
}
