package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uranium.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//

import java.util.Scanner;

public class Uranium extends RawMaterial 
{
	public Uranium()
	{
		Logger.MethodCall("Uranium()");
		Logger.MethodReturn("");
	}
	public void Perish() 
	{
		Logger.MethodCall("Perish()");
		this.SetAsteroid(null);
		Logger.MethodReturn("void");
	}
	
	public String GetUniqueID() 
	{
		Logger.MethodCall("GetUniqueID()");
		Logger.MethodReturn("String: Uranium");
		return "Uranium";
	}
	
	public void PerihelionReaction() 
	{
		Logger.MethodCall("PerihelionReaction()");
		Scanner sc = new Scanner(System.in);
		System.out.println("PerihelionReaction()");
		System.out.println("Is Holedepth = CrustTickness? [true/false]");
		String answer = sc.nextLine();
		if (answer.equals("true")) {
			this.asteroid.Explode();
			this.Perish();
		}
		sc.close();
		Logger.MethodReturn("void");
	}
		
}

