package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillOfMaterials.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class BillOfMaterials {
	private RawMaterial materials;
	public Boolean CheckInventory(RawMaterial inventory) {
		return null;
	}
	
	public void AddMaterialToBill(RawMaterial material) {
	}
	
	public RawMaterial DeleteFromInventory(RawMaterial inventory) {
		return inventory;
	}
}
