package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Robot extends SentientBeing {
	public void Move(Place place) {
	}
	
	public void Drill() {
	}	
	
	public void Die() {
	}
	
	public void Explode() {
	}
	
	public void Step() {
	}
}
