package asteroid;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Settler.java
//  @ Date : 2021.03.18.
//  @ Author : 
//
//




public class Settler extends SentientBeing {
	private RawMaterial carriedmaterials;
	private BillOfMaterials bills;
	private TeleportGate carriedteleports;
	public void Drill() {
	}
	
	public void Mine() {
	}
	
	public void Die() {
	}
	
	public void AddCarriedMaterial(RawMaterial material) {
	}
	
	public void Explode() {
	}
	
	public void BuildRobot() {
	}
	
	public void BuildTeleportGatePair() {
	}
	
	public void FillAsteroid(RawMaterial material) {
	}
	
	public void Move(Place place) {
	}
	
	public void PutTeleportGateOnAsteroid() {
	}
	
	public void Step() {
	}
	
	public void DropCarriedMaterial(RawMaterial material) {
	}
	
	public void DropCarriedTeleport(TeleportGate teleport) {
	}
}
